### ISSUE TITLE
MicroWeb SRC bug

### ISSUE THREAD

**Issue by eltoneo** [jhhoward/MicroWeb#16]
Re: 
https://www.lazybrowndog.net/freedos/virtualbox/

MicroWeb, DosLynx and Arachne Chat board:
https://tinyurl.com/yacddu53

Hi,
Booted to DOS traps MicroWeb makefile error with this '..\..\src\dos\dos' problem.

(ERROR: E059 unable to open '..\..\src\dos\dos')

Please rectify this MicroWeb src bug!
Thanks

**Comment by jhhoward** [comment]
OK so the issues with building using the DOS version of OpenWatcom:
1. No long file name support. I was able to rename Interface.* and Renderer.* to avoid these problems so this is fairly easy to resolve.
2. Limited buffer size for command arguments. If the arguments sent to wpp.exe are too long then it fails with a 'Arg list too big' error. For example this argument is too long:
`wpp lib\mtcp\tcplib\packet -0 -ml -DCFG_H="tcp.cfg" -oh -ok -ot -s -oa -ei -zp2 -zpw -we -ob -ol+ -oi+ -i=lib\mTCP\TCPINC\`
This is a pain. I would have to either rearrange the directory structure of the project (because adding lib\mTCP\ exceeds the argument buffer size) or perhaps I could rearrange the compilation of the mTCP library into a static lib and link it to the rest of the project.

**Comment by eltoneo** [comment]
> OK so the issues with building using the DOS version of OpenWatcom:
> 
> 1. No long file name support. I was able to rename Interface.* and Renderer.* to avoid these problems so this is fairly easy to resolve.
> 2. Limited buffer size for command arguments. If the arguments sent to wpp.exe are too long then it fails with a 'Arg list too big' error. For example this argument is too long:
>    `wpp lib\mtcp\tcplib\packet -0 -ml -DCFG_H="tcp.cfg" -oh -ok -ot -s -oa -ei -zp2 -zpw -we -ob -ol+ -oi+ -i=lib\mTCP\TCPINC\`
>    This is a pain. I would have to either rearrange the directory structure of the project (because adding lib\mTCP\ exceeds the argument buffer size) or perhaps I could rearrange the compilation of the mTCP library into a static lib and link it to the rest of the project.
[
O-W v2 fork supports LFN
]
(https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build)
