### ISSUE TITLE
can it work without graphics mode?

### ISSUE THREAD

**Issue by roytam1** [jhhoward/MicroWeb#3]
i.e. a new lynx browser.
so it can work on IBM MDA output.

**Comment by jhhoward** [comment]
There are no current plans for a text mode but possibly in the future. The code has been written in a way so that the video driver is separated from the rest of the renderer as much as possible so that additional video modes can be supported in the future.

MDA text mode is interesting though as it provides the option to underline text which would be useful for hyperlinks!

**Comment by niutech** [comment]
There are text-based web browsers for DOS: [DosLynx](http://macall.net/#doslynx), [Lynx](https://lynx.invisible-island.net/current/#binary_w32), [Elinks & Links](http://www.ausreg.com/dos_ports/index.htm).

**Comment by jhhoward** [comment]
Closing this as there are alternative browsers available for text mode only
